### ISSUE TITLE
提供的项目文档根本无法搭建运行环境，太不清楚了

### ISSUE THREAD

**Issue by yyzz1987431** [Yirendai/cicada#1]
1.cicada-collector,cicada-web模块 运行sh脚本有问题，根本不会编译出脚本中运行的jar。
2.cicada-demo包根本编译出来的jar包根本无法运行，麻烦把pom文件搞正确。自测通过在开源出来吧
3.cicada-dashboard npm打包无法通过，可能依赖勒你们内部的东西。

**Comment by alfredzhang** [comment]
您好，我们会再重新梳理一下文档，请问您在搭建过程中有什么问题，我们会尽力帮您解决，谢谢

**Comment by alfredzhang** [comment]
好的，谢谢，我们会尽快完善一下环境、配置和程序，重新测试，通过后通知您。如果有提供一些日志的话，感激不尽。

**Comment by alfredzhang** [comment]
我们正在重新完善文档和部署脚本，完成后通知你，谢谢。

**Comment by yyzz1987431** [comment]
1 cicada-collector,cicada-web模块 run.sh文件需要修改下，现在编译出来的版本号已经是2.0.1，脚本中还是2.0.0,编译出来的jar包名称也不对。
2.cicada-demo包pom文件不对,我已经做了修改
1. cicada-demo-consumer-web （输入http://localhost:8080/test）报错。java.lang.NoSuchMethodError: com.yirendai.infra.cicada.entity.trace.Endpoint.<in
   it>(Ljava/lang/String;I)V
   [Uploading yirendai.zip…]()

**Comment by yyzz1987431** [comment]
[yirendai.zip](https://github.com/Yirendai/cicada/files/521497/yirendai.zip)
1 cicada-collector,cicada-web模块 run.sh文件需要修改下，现在编译出来的版本号已经是2.0.1，脚本中还是2.0.0,编译出来的jar包名称也不对。
2.cicada-demo包中的pom文件不对,我已经做了修改
3. cicada-demo-consumer-web （输入http://localhost:8080/test）报错。java.lang.NoSuchMethodError: com.yirendai.infra.cicada.entity.trace.Endpoint.<in
it>(Ljava/lang/String;I)V

[yirendai.zip](https://github.com/Yirendai/cicada/files/521497/yirendai.zip)

**Comment by yyzz1987431** [comment]
[Uploading yirendai.zip…]()
修改文件
[Uploading run.txt…]()

**Comment by sealake** [comment]
感谢您的建议，已经配合版本升级，修复了执行脚本run.sh中的bug。

我们在一台干净的机器上，执行打包编译，并没有出现问题。构建环境如下：
操作系统： CentOS7.2
JDK版本：1.7 && 1.8
node版本：4.5.0 && 6.2.2 

以上配置编译cicada以及cicada-dashboard的时候并没有出现问题。方便说明一下你的构建环境么？

**Comment by yyzz1987431** [comment]
恩，构建环境如下：
操作系统:CentOS6.5
JDK版本：1.8
node版本：4.4.5
也能编译打包成功,只是在演示demo的时候会报错。我在确认下看是不是配置有问题。
