### ISSUE TITLE
环境搭建问题

### ISSUE THREAD

**Issue by z589533** [Yirendai/cicada#2]
2、**搭建nginx，配置nginx开启日志收集功能（LUA_JIT），日志将以Http Post的方式发送到nginx**

     Nginx搭建好后，修改application.yml中nginx地址，provicer和consumer都需要修改

改什么nginx地址

cicada:
  url: http://localhost:9080/upload
  sampleRate: 100
  connectTimeout: 100
  soTimeout: 100
  batchSize: 32
  bufferSize: 1024
  tpsLimit: 2048

  url: http://localhost:9080/upload这一个吗？
怎么改http://112.74.XXX.XXX:9880/upload这样？

**Comment by Melody0119** [comment]
是修改这一个配置，不过基于安全和性能方面的考虑，不建议将日志收集的服务部署在公网上，建议只在内部进行访问。

**Comment by sealake** [comment]
是修改这个配置。
这部分文档表示为了在客户端采集的数据能够POST到收集的server，需要在客户端配置上传的地址。
【PS】
基于安全和性能方面的考虑，建议将收集服务部署在内网。
